apiVersion: v1
kind: PersistentVolume
metadata:
  name: events-db-pv
  labels:
    type: local
    app: events-api
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/db"
