[package]
name = "actix-diesel-sqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
actix.workspace = true
actix-web.workspace = true
dotenvy.workspace = true
env_logger.workspace = true
log.workspace = true
uuid.workspace = true
